/**
 * @fileoverview gRPC-Web generated client stub for doctor
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.21.12
// source: doctor.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.doctor = require('./doctor_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.doctor.DoctorServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.doctor.DoctorServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.doctor.CreateDoctorRequest,
 *   !proto.doctor.DoctorResponse>}
 */
const methodDescriptor_DoctorService_CreateDoctor = new grpc.web.MethodDescriptor(
  '/doctor.DoctorService/CreateDoctor',
  grpc.web.MethodType.UNARY,
  proto.doctor.CreateDoctorRequest,
  proto.doctor.DoctorResponse,
  /**
   * @param {!proto.doctor.CreateDoctorRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.doctor.DoctorResponse.deserializeBinary
);


/**
 * @param {!proto.doctor.CreateDoctorRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.doctor.DoctorResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.doctor.DoctorResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.doctor.DoctorServiceClient.prototype.createDoctor =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/doctor.DoctorService/CreateDoctor',
      request,
      metadata || {},
      methodDescriptor_DoctorService_CreateDoctor,
      callback);
};


/**
 * @param {!proto.doctor.CreateDoctorRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.doctor.DoctorResponse>}
 *     Promise that resolves to the response
 */
proto.doctor.DoctorServicePromiseClient.prototype.createDoctor =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/doctor.DoctorService/CreateDoctor',
      request,
      metadata || {},
      methodDescriptor_DoctorService_CreateDoctor);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.doctor.GetDoctorRequest,
 *   !proto.doctor.DoctorResponse>}
 */
const methodDescriptor_DoctorService_GetDoctor = new grpc.web.MethodDescriptor(
  '/doctor.DoctorService/GetDoctor',
  grpc.web.MethodType.UNARY,
  proto.doctor.GetDoctorRequest,
  proto.doctor.DoctorResponse,
  /**
   * @param {!proto.doctor.GetDoctorRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.doctor.DoctorResponse.deserializeBinary
);


/**
 * @param {!proto.doctor.GetDoctorRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.doctor.DoctorResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.doctor.DoctorResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.doctor.DoctorServiceClient.prototype.getDoctor =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/doctor.DoctorService/GetDoctor',
      request,
      metadata || {},
      methodDescriptor_DoctorService_GetDoctor,
      callback);
};


/**
 * @param {!proto.doctor.GetDoctorRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.doctor.DoctorResponse>}
 *     Promise that resolves to the response
 */
proto.doctor.DoctorServicePromiseClient.prototype.getDoctor =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/doctor.DoctorService/GetDoctor',
      request,
      metadata || {},
      methodDescriptor_DoctorService_GetDoctor);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.doctor.GetAllDoctorsRequest,
 *   !proto.doctor.GetAllDoctorsResponse>}
 */
const methodDescriptor_DoctorService_GetAllDoctors = new grpc.web.MethodDescriptor(
  '/doctor.DoctorService/GetAllDoctors',
  grpc.web.MethodType.UNARY,
  proto.doctor.GetAllDoctorsRequest,
  proto.doctor.GetAllDoctorsResponse,
  /**
   * @param {!proto.doctor.GetAllDoctorsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.doctor.GetAllDoctorsResponse.deserializeBinary
);


/**
 * @param {!proto.doctor.GetAllDoctorsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.doctor.GetAllDoctorsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.doctor.GetAllDoctorsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.doctor.DoctorServiceClient.prototype.getAllDoctors =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/doctor.DoctorService/GetAllDoctors',
      request,
      metadata || {},
      methodDescriptor_DoctorService_GetAllDoctors,
      callback);
};


/**
 * @param {!proto.doctor.GetAllDoctorsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.doctor.GetAllDoctorsResponse>}
 *     Promise that resolves to the response
 */
proto.doctor.DoctorServicePromiseClient.prototype.getAllDoctors =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/doctor.DoctorService/GetAllDoctors',
      request,
      metadata || {},
      methodDescriptor_DoctorService_GetAllDoctors);
};


module.exports = proto.doctor;

