/**
 * @fileoverview gRPC-Web generated client stub for booking
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.21.12
// source: booking.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.booking = require('./booking_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.booking.BookingServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.booking.BookingServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.booking.BookingRequest,
 *   !proto.booking.BookingResponse>}
 */
const methodDescriptor_BookingService_CreateBooking = new grpc.web.MethodDescriptor(
  '/booking.BookingService/CreateBooking',
  grpc.web.MethodType.UNARY,
  proto.booking.BookingRequest,
  proto.booking.BookingResponse,
  /**
   * @param {!proto.booking.BookingRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.booking.BookingResponse.deserializeBinary
);


/**
 * @param {!proto.booking.BookingRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.booking.BookingResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.booking.BookingResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.booking.BookingServiceClient.prototype.createBooking =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/booking.BookingService/CreateBooking',
      request,
      metadata || {},
      methodDescriptor_BookingService_CreateBooking,
      callback);
};


/**
 * @param {!proto.booking.BookingRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.booking.BookingResponse>}
 *     Promise that resolves to the response
 */
proto.booking.BookingServicePromiseClient.prototype.createBooking =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/booking.BookingService/CreateBooking',
      request,
      metadata || {},
      methodDescriptor_BookingService_CreateBooking);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.booking.GetBookingRequest,
 *   !proto.booking.BookingResponse>}
 */
const methodDescriptor_BookingService_GetBooking = new grpc.web.MethodDescriptor(
  '/booking.BookingService/GetBooking',
  grpc.web.MethodType.UNARY,
  proto.booking.GetBookingRequest,
  proto.booking.BookingResponse,
  /**
   * @param {!proto.booking.GetBookingRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.booking.BookingResponse.deserializeBinary
);


/**
 * @param {!proto.booking.GetBookingRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.booking.BookingResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.booking.BookingResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.booking.BookingServiceClient.prototype.getBooking =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/booking.BookingService/GetBooking',
      request,
      metadata || {},
      methodDescriptor_BookingService_GetBooking,
      callback);
};


/**
 * @param {!proto.booking.GetBookingRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.booking.BookingResponse>}
 *     Promise that resolves to the response
 */
proto.booking.BookingServicePromiseClient.prototype.getBooking =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/booking.BookingService/GetBooking',
      request,
      metadata || {},
      methodDescriptor_BookingService_GetBooking);
};


module.exports = proto.booking;

