/**
 * @fileoverview gRPC-Web generated client stub for file
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.21.12
// source: file.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.file = require('./file_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.file.FileServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.file.FileServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.file.UploadFileRequest,
 *   !proto.file.FileResponse>}
 */
const methodDescriptor_FileService_UploadFile = new grpc.web.MethodDescriptor(
  '/file.FileService/UploadFile',
  grpc.web.MethodType.UNARY,
  proto.file.UploadFileRequest,
  proto.file.FileResponse,
  /**
   * @param {!proto.file.UploadFileRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.file.FileResponse.deserializeBinary
);


/**
 * @param {!proto.file.UploadFileRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.file.FileResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.file.FileResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.file.FileServiceClient.prototype.uploadFile =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/file.FileService/UploadFile',
      request,
      metadata || {},
      methodDescriptor_FileService_UploadFile,
      callback);
};


/**
 * @param {!proto.file.UploadFileRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.file.FileResponse>}
 *     Promise that resolves to the response
 */
proto.file.FileServicePromiseClient.prototype.uploadFile =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/file.FileService/UploadFile',
      request,
      metadata || {},
      methodDescriptor_FileService_UploadFile);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.file.GetFileUrlRequest,
 *   !proto.file.FileResponse>}
 */
const methodDescriptor_FileService_GetFileUrl = new grpc.web.MethodDescriptor(
  '/file.FileService/GetFileUrl',
  grpc.web.MethodType.UNARY,
  proto.file.GetFileUrlRequest,
  proto.file.FileResponse,
  /**
   * @param {!proto.file.GetFileUrlRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.file.FileResponse.deserializeBinary
);


/**
 * @param {!proto.file.GetFileUrlRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.file.FileResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.file.FileResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.file.FileServiceClient.prototype.getFileUrl =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/file.FileService/GetFileUrl',
      request,
      metadata || {},
      methodDescriptor_FileService_GetFileUrl,
      callback);
};


/**
 * @param {!proto.file.GetFileUrlRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.file.FileResponse>}
 *     Promise that resolves to the response
 */
proto.file.FileServicePromiseClient.prototype.getFileUrl =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/file.FileService/GetFileUrl',
      request,
      metadata || {},
      methodDescriptor_FileService_GetFileUrl);
};


module.exports = proto.file;

